### ISSUE TITLE
Godot Proposals Topics

### ISSUE THREAD

**Issue by Xrayez** [godot-extended-libraries/godot-ideas#15]
This is a list of related proposals at GIP which may share the same underlying need, and to keep #6 clean.

### Speeding up creation of new projects or development workflows

- [ ] godotengine/godot-proposals#65
- [ ] godotengine/godot-proposals#1360
- [ ] godotengine/godot-proposals#1365
- [ ] godotengine/godot-proposals#1419
- [x] #12
- [ ] godotengine/godot-proposals#1481
- [ ] godotengine/godot-proposals#1482
- [ ] godotengine/godot-proposals#2292
- [ ] godotengine/godot-proposals#2585
- [ ] godotengine/godot-proposals#2792
- [ ] godotengine/godot-proposals#3029

### Flattening/converting collision shapes into polygon-based shapes

- [ ] godotengine/godot-proposals#199
- [ ] godotengine/godot-proposals#564
- [ ] godotengine/godot-proposals#1925
- [ ] godotengine/godot-proposals#1126
- [ ] godotengine/godot-proposals#1157

### Static methods

**Keywords**: *static method*, *instance*, *singleton*

- [ ] godotengine/godot-proposals#1101
- [ ] godotengine/godot-proposals#391
- [ ] godotengine/godot-proposals#2312
- [ ] godotengine/godot-proposals#1741

### Machine learning/Neural networks

- [ ] godotengine/godot-proposals#2506
- [ ] godotengine/godot#30613
- [ ] godotengine/godot-proposals#1577

### Node composition/hierarchy and organization

- [ ] godotengine/godot-proposals#627
- [ ] godotengine/godot-proposals#2544
- [ ] godotengine/godot-proposals#724
- [x] godotengine/godot-proposals#2796
