### ISSUE TITLE
[TRACKER] Yielding to `completed` signal related issues discussion

### ISSUE THREAD

**Issue by Xrayez** [godot-extended-libraries/godot-ideas#3]
I'd like to integrate all the proposals and discussions regarding yielding to `completed` signal or some kind of "waiting for signal" concepts as people seem to report certain difficulties in understanding which leads to mixing of existing concepts.

### Issues/proposals
- [ ] Add `await` keyword (godotengine/godot#22947)
- [ ] Use "completed" as default parameter for yield() (godotengine/godot#21039)
- [ ] Separate signal-waiting from coroutine calls (godotengine/godot#7618)
- [ ] Separate coroutine calls from function calls (godotengine/godot#7617)
- [ ] Add support for code animation (godotengine/godot-proposals#1105).

### Pull requests
- [ ] Add `await` keyword as alias for yield(async_func(), "completed") godotengine/godot#23369
- [ ] Add `await` operator to GDScript godotengine/godot#32034.

## Godot Docs
https://github.com/godotengine/godot-docs/pull/2644

## How others use it
[GUT - Yielding - How Yielding and Gut Works](https://github.com/bitwes/Gut/wiki/Yielding#how-yielding-and-gut-works)

**Comment by Xrayez** [comment]
Godot 4.x introduces `await` keyword in development versions, there's not much value in this tracker.
